export * from "./header";
export * from "./home";
export * from "./about";
export * from "./projects";
export * from "./work";
export * from "./workFooter";
export * from "./imageSlider";
export * from "./gradientContainer";
export * from "./shinyCards";
